### ISSUE TITLE
input upper case,search failed

### ISSUE THREAD

**Issue by feilie** [McFizh/tinySelect#1]
It is a good JQuery Plug-in,however when i input upper case to search options,
it loses efficacy.After debugging, I found a problem with the following code
`sval = $(e.currentTarget).val();`
Then I modified the code like this and search upper case successfully:
`sval = $(e.currentTarget).val().toLowerCase();`

**Comment by McFizh** [comment]
Thanks for the feedback. I've added 'searchCaseSensitive' option to the plugins configuration object. This makes the search either fully case sensitive or insensitive.
