### ISSUE TITLE
IE8会有什么问题？

### ISSUE THREAD

**Issue by zanseven007** [McFizh/tinySelect#2]
我想用一下你的这个插件放在一个后台管理系统里面，但是我需要支持IE8。请问一下IE8下会有什么问题？

**Comment by McFizh** [comment]
Sorry, but you're not making any sense, please write your question in english. 

If you are asking about ie8 support, then the answer is: no, I won't add any ie hacks to code. If the problem is repeatable on modern browsers, then I will fix it.

**Comment by zanseven007** [comment]
Thx,  ie8 support , That is what I want to say, What a pity.
